apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eureka-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: eureka.example.com   # Use real DNS in production
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eureka-server-service
                port:
                  number: 8761
