apiVersion: v1
kind: Service
metadata:
  name: eureka-server-service
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761       # Service port
      targetPort: 8761 # Container port
      nodePort: 8761   # NodePort (exposes this port on the host)
  type: NodePort       # <-- Change from ClusterIP to NodePort
