apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80       # Port exposed by the service
      targetPort: 8080  # Port your app container listens on
  type: NodePort